ui:
  container_name: qc-ui
  image: xblaster/quickcooking-ui
  ports:
   - 9000:9000
  environment:
   - ELASTIC=elastic:9200
   - imageVolume=/images
  volumes:
    - /volumes/qc/images:/images
  links:
   - elastic
  command: "grunt serve:dist --force"
elastic:
  image: elasticsearch
  container_name: qc-elastic
